[global]
developmentMode = false

[server]
runOnSave = true
port = 8501
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#1E293B"
font = "sans serif"

[runner]
magicEnabled = true

[logger]
level = "info"